version: '2'
services:
  ibgw:
    build:
      context: ./ibheadless
      dockerfile: Dockerfile
    image:  ibgw
    container_name: ibgw
    restart: always
    environment:
      - IB_IbLoginId
      - IB_IbPassword
    ports:
      - "4001-4003:4001-4003"
  ibrest:
    build:
      context: .
      dockerfile: Dockerfile
    image: ibrest
    container_name: ibrest
    restart: always
    environment:
      - IBGW_PORT_4003_TCP_ADDR=ibgw
      - IBGW_CLIENT_ID=0
      - IBREST_HOST=0.0.0.0
      - IBREST_PORT=443
    links:
      - ibgw
    ports:
      - "443:443"
